#!/usr/bin/env python

import rospy
from geometry_msgs.msg import Twist
from turtlesim.msg import Pose
from math import degrees, radians

MAX_ANG_SPD = 2.84
ANG_SPD = 0.25 * MAX_ANG_SPD


pose = Pose()

tw   = Twist()

def cb_get_pose(msg):   
     global pose
     pose = msg


def get_org():
     return pose.theta  

if __name__=='__main__':

     rospy.init_node("sub_turtle_pose")
     rospy.Subscriber("/turtle1/pose", Pose, cb_get_pose)
     pub = rospy.Publisher("/turtle1/cmd_vel", Twist, queue_size = 10)

     angle = radians(input("input angle(deg) to rotate: "))

     start_theta = get_org()
     target_theta = start_theta + angle
     '''
     if degrees(target_theta) >= 180:
          target_theta = radians(degrees(target_theta) - 360)
     elif degrees(target_theta) <= -180:
          target_theta = -radians(degrees(target_theta) + 360)
'''
     print ('target_theta = ', target_theta)
     
     if angle >= 0:
	          tw.angular.z = ANG_SPD
	          while target_theta >= pose.theta:
	               print ('pose.theta = ', pose.theta)
	               pub.publish(tw)

	     else:
	          tw.angular.z = -ANG_SPD
	          while target_theta <= pose.theta:
	               pub.publish(tw)

     tw.angular.z = 0.0; pub.publish(tw)

     rospy.spin()
